name: nosmai_camera_sdk
description: A Flutter plugin for Nosmai SDK - Real-time video filtering and beauty effects
version: 2.0.1+1
homepage: https://github.com/nosmai/nosmai_camera_sdk_flutter
repository: https://github.com/nosmai/nosmai_camera_sdk_flutter
documentation: https://github.com/nosmai/nosmai_camera_sdk_flutter#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nosmai.nosmai_flutter
        pluginClass: NosmaiFlutterPlugin
      ios:
        pluginClass: NosmaiFlutterPlugin